name: python-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - plotly
  - scikit-learn
  - cufflinks
  - random
  - scipy
  - os
  - sqlalchemy
  - requests
  - bs4
  - ipython
  - pip
