name: python-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - sqlalchemy
  - requests
  - bs4
  - ipython
  - xlrd
  - lxml
  - cufflinks-py
  - pip
  - six
  - pydot
